skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "DqdgQv57RWZ4RVUQ7v6SMvTfA11gFph2TNKZDz7sa3Ap"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
